name: signin_with_linkedin
description: A flutter plugin that helps to sign in with linkedin (Social sign in)
version: 0.0.1
homepage: https://auberginesolutions.com
repository: https://github.com/nayanAubie/signin_with_linkedin

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  uuid: ^4.0.0
  webview_flutter: ^4.2.4

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

